// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrSV66oJ8JOTLVgmOIWnw40A9pyVYtLg',
    appId: '1:54270909902:web:fc067046af039cc1ea9f9f',
    messagingSenderId: '54270909902',
    projectId: 'tic-tac-toe-number1',
    authDomain: 'tic-tac-toe-number1.firebaseapp.com',
    storageBucket: 'tic-tac-toe-number1.firebasestorage.app',
    measurementId: 'G-K1YFEQ8K7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPnscTlwms3V0zEXaBVNflZHuZgfGnzg',
    appId: '1:54270909902:android:385ebbe28f2b9776ea9f9f',
    messagingSenderId: '54270909902',
    projectId: 'tic-tac-toe-number1',
    storageBucket: 'tic-tac-toe-number1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_-DGvAzRuhkSqNlpPui2Kype5Aw9A_Q',
    appId: '1:54270909902:ios:d9a40f5f35a9eb28ea9f9f',
    messagingSenderId: '54270909902',
    projectId: 'tic-tac-toe-number1',
    storageBucket: 'tic-tac-toe-number1.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );
}
